### ISSUE TITLE
Documentation slide: Wrong french text

### ISSUE THREAD

**Issue by batden** [BodhiDev/bodhi-slideshow-new#9]
Error in https://github.com/BodhiDev/bodhi-slideshow-new/blob/master/slides/l10n/fr/documentation.html

The correct translation is available here: https://github.com/batden/Translations-for-Bodhi/blob/master/documentation_fr.txt

Thank you,
Philippe

**Comment by thewaiter** [comment]
Make a pull request pls

Stefan
